"""initial

Revision ID: 37aea75c5008
Revises: 6fd2d54507ad
Create Date: 2026-06-10 19:59:12.689988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37aea75c5008'
down_revision: Union[str, None] = '6fd2d54507ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
